// Skills Manager - Load, save, reset, and manage automation skill files.
// Bundled skills live in skills/*.txt (fetched via chrome.runtime.getURL).
// User customisations / new skills are persisted in chrome.storage.local.

const BUNDLED_SKILL_IDS = ['x_com'];

export class SkillsManager {

  // ── Parse ──────────────────────────────────────────────────────────────────
  // Parses a .txt skill file into { meta, body }.
  // Header: lines of "key: value" before the first "---" separator.
  _parse(content, id) {
    const lines = content.split('\n');
    const meta = { id, name: id, domain: '', description: '', version: '1.0', bundled: false, modified: false };
    let bodyStart = 0;

    for (let i = 0; i < lines.length; i++) {
      if (lines[i].trim() === '---') {
        bodyStart = i + 1;
        break;
      }
      const colonIdx = lines[i].indexOf(':');
      if (colonIdx > 0) {
        const key = lines[i].slice(0, colonIdx).trim().toLowerCase();
        const val = lines[i].slice(colonIdx + 1).trim();
        if (['name', 'domain', 'description', 'version'].includes(key)) {
          meta[key] = val;
        }
      }
    }

    const body = lines.slice(bodyStart).join('\n').trim();
    return { meta, body };
  }

  // Build a full .txt content string from parts (used when creating skills).
  buildContent(name, domain, description, body) {
    let out = `name: ${name}\n`;
    if (domain)      out += `domain: ${domain}\n`;
    if (description) out += `description: ${description}\n`;
    out += `version: 1.0\n`;
    out += `---\n`;
    out += body || '';
    return out;
  }

  // ── Load bundled skill ─────────────────────────────────────────────────────
  async _loadBundled(id) {
    try {
      const url = chrome.runtime.getURL(`skills/${id}.txt`);
      const resp = await fetch(url);
      if (!resp.ok) return null;
      const text = await resp.text();
      const { meta, body } = this._parse(text, id);
      meta.bundled = true;
      return { meta, body, rawContent: text };
    } catch {
      return null;
    }
  }

  // ── Public: get all skills ─────────────────────────────────────────────────
  async getSkills() {
    const skills = [];

    // 1. Bundled skills (with optional user overrides)
    for (const id of BUNDLED_SKILL_IDS) {
      const bundled = await this._loadBundled(id);
      if (!bundled) continue;

      const storageKey = `skill_custom_${id}`;
      const data = await chrome.storage.local.get(storageKey);
      const customContent = data[storageKey];

      if (customContent !== undefined) {
        const { meta, body } = this._parse(customContent, id);
        skills.push({
          ...meta,
          bundled: true,
          modified: true,
          body,
          rawContent: customContent,
          defaultBody: bundled.body,
          defaultRaw: bundled.rawContent
        });
      } else {
        skills.push({
          ...bundled.meta,
          body: bundled.body,
          rawContent: bundled.rawContent,
          defaultBody: bundled.body,
          defaultRaw: bundled.rawContent
        });
      }
    }

    // 2. User-created custom skills
    const data = await chrome.storage.local.get('skillCustomIds');
    const customIds = data.skillCustomIds || [];
    for (const id of customIds) {
      const d = await chrome.storage.local.get(`skill_custom_${id}`);
      const content = d[`skill_custom_${id}`];
      if (!content) continue;
      const { meta, body } = this._parse(content, id);
      skills.push({ ...meta, bundled: false, modified: false, body, rawContent: content });
    }

    return skills;
  }

  // ── Public: save user edit (bundled override or custom update) ─────────────
  async saveSkill(id, rawContent) {
    await chrome.storage.local.set({ [`skill_custom_${id}`]: rawContent });
  }

  // ── Public: reset bundled skill back to default ────────────────────────────
  async resetSkill(id) {
    await chrome.storage.local.remove(`skill_custom_${id}`);
  }

  // ── Public: create a new custom skill ─────────────────────────────────────
  // id is auto-generated by caller (slugified name + timestamp suffix if needed)
  async createSkill(id, rawContent) {
    await chrome.storage.local.set({ [`skill_custom_${id}`]: rawContent });
    if (!BUNDLED_SKILL_IDS.includes(id)) {
      const data = await chrome.storage.local.get('skillCustomIds');
      const ids = data.skillCustomIds || [];
      if (!ids.includes(id)) {
        ids.push(id);
        await chrome.storage.local.set({ skillCustomIds: ids });
      }
    }
  }

  // ── Public: delete a custom skill (bundled skills cannot be deleted) ────────
  async deleteSkill(id) {
    if (BUNDLED_SKILL_IDS.includes(id)) {
      throw new Error('Bundled skills cannot be deleted. Use reset instead.');
    }
    await chrome.storage.local.remove(`skill_custom_${id}`);
    const data = await chrome.storage.local.get('skillCustomIds');
    const ids = (data.skillCustomIds || []).filter(i => i !== id);
    await chrome.storage.local.set({ skillCustomIds: ids });
  }

  // ── Public: build prompt appendix from selected skills ────────────────────
  // mode: 'auto'   → include all skills
  //       'manual' → include only skills whose id is in selectedIds
  getSkillsForPrompt(allSkills, selectedIds = [], mode = 'auto') {
    const toInclude = mode === 'auto' ? allSkills : allSkills.filter(s => selectedIds.includes(s.id));
    if (toInclude.length === 0) return '';

    let block = '\n\n## SKILLS / DOMAIN KNOWLEDGE\n';
    block += 'Use the following domain knowledge to perform tasks faster and more reliably. Apply only what is relevant to the current task.\n\n';
    for (const skill of toInclude) {
      block += `### ${skill.name}${skill.domain ? ` (${skill.domain})` : ''}\n`;
      block += skill.body + '\n\n';
    }
    return block.trimEnd();
  }
}
